language: php

matrix:
  include:
    - php: 7.3.3
      dist: bionic
    - php: 7.3.4
      dist: bionic
    - php: 7.3.5
      dist: bionic
    - php: 7.3.6
      dist: bionic

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; else composer install; fi
  - if [ "$psalm" = "yes" ]; then composer require --dev vimeo/psalm; fi

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - if [ "$psalm" = "yes" ]; then vendor/bin/psalm; fi

after_script:
  - php vendor/bin/coveralls
